IA_try_django/mysite/mysite/urls.py
#-*- coding:utf-8 -*-
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')), # polls/urls.py module include
    path('news/', include('news.urls')),
]

IA_try_django/mysite/news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('articles/', views.Archive.as_view(), name="archive"),
    path('articles/<int:pk>', views.ArticleDetail.as_view(), name="detail"),
    path('articles/<int:year>/', views.YearArchive.as_view(), name='year_archive'),
    path('articles/<int:year>/<int:month>/', views.MonthArchive.as_view(), name='month_archive'),
    path('articles/<int:year>/<int:month>/<int:day>/', views.DayArchive.as_view(), name="day_archive"),
]

IA_try_django/mysite/polls/urls.py
from django.urls import path

from . import views
# each app has urls.py -> can manage url easily in mysite urls.py
app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

IA_try_django/mysite/news/models.py
from django.db import models
from django.urls import reverse

class Reporter(models.Model):
    full_name = models.CharField(max_length=70)

    def __str__(self):
        return self.full_name


class Article(models.Model):
    pub_date = models.DateField()
    headline = models.CharField(max_length=200)
    content = models.TextField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline
    
    def get_absolute_url(self):
        return reverse("news:detail", args=(self.id,))
    

IA_try_django/mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# create database
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0) # 몇명이 설문에 응답했는가

    def __str__(self):
        return self.choice_text

IA_try_django/mysite/news/views.py
from django.shortcuts import render
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import *

from .models import Article, Reporter

class Archive(ArchiveIndexView):
    model = Article
    date_field = "pub_date"
    template_name = "news/archive.html"

class ArticleDetail(DetailView):
    model = Article
    template_name = 'news/detail.html'

class YearArchive(YearArchiveView):
    model = Article
    date_field = "pub_date"
    make_object_list=True
    template_name = 'news/year_archive.html'

class MonthArchive(MonthArchiveView):
    model = Article
    date_field = "pub_date"
    template_name = 'news/month_archive.html'
    month_format = '%m'

class DayArchive(DayArchiveView):
    model = Article
    date_field = "pub_date"
    template_name = 'news/day_archive.html'
    month_format = '%m'

IA_try_django/mysite/polls/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

IA_try_django/mysite/news/templates/news/archive.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'news/style.css' %}">
<head>
    <meta charset="utf-8">
</head>
<body>
    <p id="archives">Article Archives</p>
    <ul>
    {% for date in date_list %}
        <li>
            <a href="{% url 'news:year_archive' date|date:'Y' %}"><p id="year">{{ date|date:'Y'}}</p></a>
        </li>
    {% endfor %}
</body>

IA_try_django/mysite/news/templates/news/day_archive.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'news/style.css' %}">
<head>
    <meta charset="utf-8">
</head>
<body>
    <p id="archives">Article Archives for {{ day|date:'d, N, Y'}}</p>

    <div>
        <ul>
            {% for article in object_list %}
            <li><strong>{{ article.pub_date|date:"Y/m/d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ article.get_absolute_url }}">{{ article.headline }}</strong></a></li>
            {% endfor %}
        </ul>
    </div>
</body>

IA_try_django/mysite/news/templates/news/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'news/style.css' %}">

<head>
    <meta charset="utf-8">
    <img src="{% static 'news/images/sitelogo.png' %}">
</head>
<body>
    <p id="headline"><strong>"{{ object.headline }}"</strong></p>
    <hr>
    <div>
        <p id="content">{{ object.content }}</p>
    </div>
    <br>
    <hr>
    <div>
    <span> {{ object.pub_date}} </span><br>
    <span> reporter:&nbsp;{{ object.reporter }} </span>
    </div>
</body>

IA_try_django/mysite/news/templates/news/month_archive.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'news/style.css' %}">
<head>
    <meta charset="utf-8">
</head>
<body>
    <p id="archives">Article Archives for {{ month|date:"N, Y"}}</p>
    {% for date in date_list %}
    <a href="{% url 'news:day_archive' date|date:'Y' month|date:'m' date|date:'d' %}">
    <p id="day">Day&nbsp;{{ date|date:'d' }}</p></a>
        <ul>
        {% for article in object_list %}
            {% if date|date:'d' == article.pub_date|date:"d" %}
                <li><strong>{{ article.pub_date|date:"Y/m/d" }}&nbsp;&nbsp;&nbsp; 
                <a href="{{ article.get_absolute_url }}">{{ article.headline }}</strong></a></li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endfor %}
</body>

IA_try_django/mysite/news/templates/news/year_archive.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'news/style.css' %}">
<head>
    <meta charset="utf-8">
</head>
<body>
    <p id="archives">Article Archives for {{ year|date:"Y" }}<p>
    {% for date in date_list %}
        <a href="{% url 'news:month_archive' year|date:'Y' date|date:'m' %}">
        <p id="month">{{ date|date:'F' }}</p></a>
        <ul>
        {% for article in object_list%}
            {% if date|date:'m' == article.pub_date|date:"m" %}
                <li><strong>{{article.pub_date|date:"Y/m/d"}}&nbsp;&nbsp;&nbsp;
                <a href="{{ article.get_absolute_url }}">{{ article.headline }}</strong></a></li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endfor %}
</body>

IA_try_django/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

IA_try_django/mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

IA_try_django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>